version: "3.5"

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - "4200:4200"
    command: "ng serve --host 0.0.0.0"

